@baseUrl = http://localhost:4000/api
# Si ya lo estás probando directo en la nube de Render, usa tu URL de Render:
# @baseUrl = https://tu-proyecto.onrender.com/api

### ==========================================
### 1. PROBAR USUARIOS (Enfermeros)
### ==========================================

### Crear un usuario con los campos nuevos (Turno Enum)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "nombre": "Enf. Laura Medina",
  "email": "laura.medina@casadelsol.mx",
  "usuario": "laura_medina",
  "password": "securepassword123",
  "turno": "Matutino"
}

### Obtener lista de usuarios
GET {{baseUrl}}/users


### ==========================================
### 2. PROBAR PASTILLAS (Inventario / Slots)
### ==========================================

### Crear una pastilla (Slot 1, con stock inicial y horas)
POST {{baseUrl}}/pills
Content-Type: application/json

{
  "nombre": "Metformina",
  "dosis": "850 mg",
  "slotCompartimento": 1,
  "stockActual": 30,
  "stockMinimoAlerta": 5,
  "fechaInicio": "2026-09-26T00:00:00.000Z",
  "recurrencia": {
    "tipo": "intervalo",
    "intervaloHoras": 8,
    "horas": ["08:00", "14:00", "22:00"]
  }
}

### Obtener lista de pastillas
GET {{baseUrl}}/pills


### ==========================================
### 3. PROBAR PACIENTES (Con Colores Enum y Género)
### ==========================================

### Crear un paciente (Asegúrate de poner un ID de pastilla válido de arriba)
POST {{baseUrl}}/patients
Content-Type: application/json

{
  "nombre": "Carmen Ruiz",
  "edad": 82,
  "genero": "Femenino",
  "colorTarjeta": "Azul",
  "porcentajeAdherencia": 96,
  "pastillas": [
    "6ab7647ef90063d37df0c130"
  ]
}

### Obtener pacientes con sus pastillas "populadas"
GET {{baseUrl}}/patients
